liip_imagine:
    # As mentioned above, gd, imagick or gmagick are possible
    driver: "gd"

    # This is where all the filters sets are located
    filter_sets: 
        ensembles:
            filters:
                scale:
                    dim: [320,290]
        produits:
            filters:
                scale:
                    dim: [190,270]

#bin/console liip:imagine:cache:remove