liip_imagine:
    # As mentioned above, gd, imagick or gmagick are possible
    driver: "gd"

    # This is where all the filters sets are located
    filter_sets: 
        ensembles:
            filters:
               fixed:
                    width: 320
                    height: 292

        produits:
            filters:
                fixed:
                    width: 380
                    height: 450

#bin/console liip:imagine:cache:remove