twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['form/base.html.twig']
    globals:
        init: '@App\Controller\HomeController'
        admin: '@App\Controller\AdminController'