vich_uploader:
    db_driver: orm

    mappings:
        products:
            uri_prefix: '%images_products%'
            upload_destination: '%kernel.project_dir%/public%images_products%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        ensembles:
            uri_prefix: '%images_ensembles%'
            upload_destination: '%kernel.project_dir%/public%images_ensembles%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        banniere:
            uri_prefix: '%images_banniere%'
            upload_destination: '%kernel.project_dir%/public%images_banniere%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
